# Verify all six platform hash artifacts contain the same complete frame and
# audio inventory. Run this from CI with -DROOT=<artifact directory> -P this file.

cmake_minimum_required(VERSION 3.25)

include("${CMAKE_CURRENT_LIST_DIR}/../holymapperel/roms.cmake")
# 36 game and movie rows, plus one frame row per Holy Mapperel ROM and one more
# (the .saved key) for each ROM whose entry ends in :save.
list(LENGTH NESTURBATOR_HOLYMAPPEREL_ROMS holymapperel_count)
set(holymapperel_saved_count 0)
foreach(entry IN LISTS NESTURBATOR_HOLYMAPPEREL_ROMS)
  if(entry MATCHES ":save$")
    math(EXPR holymapperel_saved_count "${holymapperel_saved_count} + 1")
  endif()
endforeach()
math(EXPR expected_rows "36 + ${holymapperel_count} + ${holymapperel_saved_count}")

function(validate_hash_inventory root out_ok out_error)
  file(GLOB candidates LIST_DIRECTORIES true "${root}/hashes-*")
  set(directories)
  foreach(candidate IN LISTS candidates)
    if(IS_DIRECTORY "${candidate}")
      list(APPEND directories "${candidate}")
    endif()
  endforeach()
  list(LENGTH directories directory_count)
  if(NOT directory_count EQUAL 6)
    set(${out_ok} FALSE PARENT_SCOPE)
    set(${out_error} "expected 6 platform artifacts, found ${directory_count}" PARENT_SCOPE)
    return()
  endif()

  set(expected_keys)
  foreach(game IN ITEMS nesteroids dabg rhde)
    list(APPEND expected_keys "${game}/boot/audio/pcm sha256")
    list(APPEND expected_keys "${game}/boot/audio/transitions sha256")
    foreach(frame IN ITEMS 1 30 60 120 180)
      list(APPEND expected_keys "${game}/boot/frame ${frame}")
    endforeach()
  endforeach()
  foreach(port IN ITEMS p0 p1 both)
    foreach(frame IN ITEMS 1 30 60 120 180)
      list(APPEND expected_keys "dabg/${port}/frame ${frame}")
    endforeach()
  endforeach()
  foreach(entry IN LISTS NESTURBATOR_HOLYMAPPEREL_ROMS)
    string(REPLACE ":" ";" parts "${entry}")
    list(GET parts 0 hm_key)
    list(GET parts 2 hm_n)
    list(APPEND expected_keys "holymapperel/${hm_key}/frame ${hm_n}")
    if(entry MATCHES ":save$")
      list(APPEND expected_keys "holymapperel/${hm_key}.saved/frame ${hm_n}")
    endif()
  endforeach()
  list(SORT expected_keys)

  set(actual_keys)
  set(first_contents "")
  foreach(directory IN LISTS directories)
    set(hash_file "${directory}/hashes.txt")
    if(NOT EXISTS "${hash_file}" OR IS_DIRECTORY "${hash_file}")
      set(${out_ok} FALSE PARENT_SCOPE)
      set(${out_error} "${hash_file} is missing" PARENT_SCOPE)
      return()
    endif()

    file(READ "${hash_file}" contents)
    string(FIND "${contents}" "\r" cr_position)
    if(NOT cr_position EQUAL -1)
      set(${out_ok} FALSE PARENT_SCOPE)
      set(${out_error} "${hash_file} contains CR line endings" PARENT_SCOPE)
      return()
    endif()
    if(first_contents STREQUAL "")
      set(first_contents "${contents}")
    elseif(NOT contents STREQUAL first_contents)
      set(${out_ok} FALSE PARENT_SCOPE)
      set(${out_error} "${hash_file} differs from the first platform artifact" PARENT_SCOPE)
      return()
    endif()

    file(STRINGS "${hash_file}" rows)
    list(LENGTH rows row_count)
    if(NOT row_count EQUAL expected_rows)
      set(${out_ok} FALSE PARENT_SCOPE)
      set(${out_error} "${hash_file} has ${row_count} rows; expected ${expected_rows}" PARENT_SCOPE)
      return()
    endif()
    set(sorted_rows ${rows})
    list(SORT sorted_rows)
    if(NOT "${rows}" STREQUAL "${sorted_rows}")
      set(${out_ok} FALSE PARENT_SCOPE)
      set(${out_error} "${hash_file} is not sorted" PARENT_SCOPE)
      return()
    endif()

    set(actual_keys)
    foreach(row IN LISTS rows)
      if("${row}" MATCHES "^([^ ]+) sha256 ([0-9a-f]+)$")
        set(key "${CMAKE_MATCH_1} sha256")
        set(digest "${CMAKE_MATCH_2}")
      elseif("${row}" MATCHES "^([^ ]+) ([0-9]+) ticks ([0-9]+) sha256 ([0-9a-f]+)$")
        set(key "${CMAKE_MATCH_1} ${CMAKE_MATCH_2}")
        set(digest "${CMAKE_MATCH_4}")
      else()
        set(${out_ok} FALSE PARENT_SCOPE)
        set(${out_error} "${hash_file} has malformed row: ${row}" PARENT_SCOPE)
        return()
      endif()
      string(LENGTH "${digest}" digest_length)
      if(NOT digest_length EQUAL 64)
        set(${out_ok} FALSE PARENT_SCOPE)
        set(${out_error} "${hash_file} has a non-SHA256 digest in row: ${row}" PARENT_SCOPE)
        return()
      endif()
      list(APPEND actual_keys "${key}")
    endforeach()
  endforeach()

  list(SORT actual_keys)
  if(NOT "${actual_keys}" STREQUAL "${expected_keys}")
    set(${out_ok} FALSE PARENT_SCOPE)
    set(${out_error} "platform artifacts do not contain the expected ${expected_rows}-key inventory" PARENT_SCOPE)
    return()
  endif()

  set(${out_ok} TRUE PARENT_SCOPE)
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(write_hash_fixture root digest)
  file(REMOVE_RECURSE "${root}")
  foreach(platform IN ITEMS linux-arm64 linux-x64 macos-arm64 macos-x64 windows-arm64 windows-x64)
    set(rows)
    foreach(game IN ITEMS nesteroids dabg rhde)
      list(APPEND rows "${game}/boot/audio/pcm sha256 ${digest}")
      list(APPEND rows "${game}/boot/audio/transitions sha256 ${digest}")
      foreach(frame IN ITEMS 1 30 60 120 180)
        list(APPEND rows "${game}/boot/frame ${frame} ticks 714792 sha256 ${digest}")
      endforeach()
    endforeach()
    foreach(port IN ITEMS p0 p1 both)
      foreach(frame IN ITEMS 1 30 60 120 180)
        list(APPEND rows "dabg/${port}/frame ${frame} ticks 714792 sha256 ${digest}")
      endforeach()
    endforeach()
    foreach(entry IN LISTS NESTURBATOR_HOLYMAPPEREL_ROMS)
      string(REPLACE ":" ";" parts "${entry}")
      list(GET parts 0 hm_key)
      list(GET parts 2 hm_n)
      list(APPEND rows "holymapperel/${hm_key}/frame ${hm_n} ticks 714792 sha256 ${digest}")
      if(entry MATCHES ":save$")
        list(APPEND rows "holymapperel/${hm_key}.saved/frame ${hm_n} ticks 714792 sha256 ${digest}")
      endif()
    endforeach()
    list(SORT rows)
    list(JOIN rows "\n" contents)
    file(MAKE_DIRECTORY "${root}/hashes-${platform}")
    file(WRITE "${root}/hashes-${platform}/hashes.txt" "${contents}")
  endforeach()
endfunction()

if(SELFTEST)
  if(NOT DEFINED WORK)
    message(FATAL_ERROR "hash_inventory.cmake self-test requires -DWORK=<temporary directory>")
  endif()
  set(digest "0000000000000000000000000000000000000000000000000000000000000000")
  set(other_digest "1111111111111111111111111111111111111111111111111111111111111111")
  write_hash_fixture("${WORK}" "${digest}")
  validate_hash_inventory("${WORK}" valid error)
  if(NOT valid)
    message(FATAL_ERROR "valid inventory rejected: ${error}")
  endif()

  set(first_file "${WORK}/hashes-linux-arm64/hashes.txt")
  file(READ "${first_file}" contents)
  string(REPLACE "dabg/boot/audio/pcm sha256 ${digest}"
    "dabg/boot/audio/pcm malformed ${digest}" malformed_contents "${contents}")
  file(WRITE "${first_file}" "${malformed_contents}")
  validate_hash_inventory("${WORK}" valid error)
  if(valid)
    message(FATAL_ERROR "malformed audio row was accepted")
  endif()

  write_hash_fixture("${WORK}" "${digest}")
  set(second_file "${WORK}/hashes-linux-x64/hashes.txt")
  file(READ "${second_file}" contents)
  string(REPLACE "dabg/boot/audio/pcm sha256 ${digest}"
    "dabg/boot/audio/pcm sha256 ${other_digest}" changed_contents "${contents}")
  file(WRITE "${second_file}" "${changed_contents}")
  validate_hash_inventory("${WORK}" valid error)
  if(valid)
    message(FATAL_ERROR "non-identical platform inventories were accepted")
  endif()
  message(STATUS "hash inventory checker self-test passed")
  return()
endif()

if(NOT DEFINED ROOT)
  message(FATAL_ERROR "hash_inventory.cmake requires -DROOT=<artifact directory>")
endif()
get_filename_component(root "${ROOT}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
validate_hash_inventory("${root}" valid error)
if(NOT valid)
  message(FATAL_ERROR "hash inventory check failed: ${error}")
endif()
message(STATUS "six platform artifacts contain the same complete ${expected_rows}-key inventory")
