# Offline checks of the blargg MMC3 oracle's inputs (09 D-10, D-11).
#
#   cmake -DMODE=pins -DSOURCE_DIR=<repo> -P mmc3_oracle_inventory.cmake
#   cmake -DMODE=inventory -DSOURCE_DIR=<repo> -P mmc3_oracle_inventory.cmake
#
# MODE=pins checks tests/mmc3/pins.txt: a header with a 40-hex commit and the
# licence word none-stated, then 12 lines "<sha256>  <path>  <size>" with a
# 64-hex hash, a decimal size, and LF endings only.
# MODE=inventory checks tests/mmc3/oracle.txt against the pins: exactly the 12
# pinned keys, five tab-separated fields per row, status pass or unsupported,
# code 0xNN, decimal frames, and exactly the two NEC-revision keys unsupported
# (a Sharp-revision failure is never recorded as unsupported).

cmake_minimum_required(VERSION 3.25)

if(NOT SOURCE_DIR OR NOT MODE)
  message(FATAL_ERROR "mmc3_oracle_inventory: SOURCE_DIR and MODE are required")
endif()
set(pins "${SOURCE_DIR}/tests/mmc3/pins.txt")
set(table "${SOURCE_DIR}/tests/mmc3/oracle.txt")
set(nec_keys "mmc3_test_2/6-MMC3_alt;mmc3_irq_tests/5.MMC3_rev_A")

# Fills pinned_keys with the key (path without rom_singles/ and .nes) of each pin line.
function(read_pins)
  file(READ "${pins}" text)
  if(text MATCHES "\r")
    message(FATAL_ERROR "mmc3.pins: pins.txt has a carriage return; LF endings only")
  endif()
  if(NOT text MATCHES "\n$")
    message(FATAL_ERROR "mmc3.pins: pins.txt does not end with a newline")
  endif()
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" lines "${text}")
  list(LENGTH lines n)
  if(NOT n EQUAL 13)
    message(FATAL_ERROR "mmc3.pins: pins.txt has ${n} lines, expected a header and 12 ROMs")
  endif()
  list(GET lines 0 head)
  if(NOT head MATCHES "^repo https://[^ ]+ commit ([0-9a-f]+) path [^ ]+ licence none-stated$")
    message(FATAL_ERROR "mmc3.pins: line 1 is not 'repo <url> commit <sha> path <dirs> licence none-stated'")
  endif()
  string(LENGTH "${CMAKE_MATCH_1}" len)
  if(NOT len EQUAL 40)
    message(FATAL_ERROR "mmc3.pins: line 1: the commit is not 40 hex digits")
  endif()
  list(REMOVE_AT lines 0)
  set(keys)
  foreach(line IN LISTS lines)
    if(NOT line MATCHES "^([0-9a-f]+)  ([^ ]+)  ([0-9]+)$")
      message(FATAL_ERROR "mmc3.pins: not '<sha256>  <path>  <size>': ${line}")
    endif()
    string(LENGTH "${CMAKE_MATCH_1}" len)
    if(NOT len EQUAL 64)
      message(FATAL_ERROR "mmc3.pins: the hash is not 64 hex digits: ${line}")
    endif()
    set(path "${CMAKE_MATCH_2}")
    string(REPLACE "/rom_singles/" "/" key "${path}")
    string(REGEX REPLACE "\\.nes$" "" key "${key}")
    if(NOT key MATCHES "^mmc3_(test_2|irq_tests)/[^/]+$")
      message(FATAL_ERROR "mmc3.pins: unexpected path ${path}")
    endif()
    list(APPEND keys "${key}")
  endforeach()
  set(pinned_keys "${keys}" PARENT_SCOPE)
endfunction()

read_pins()

if(MODE STREQUAL "pins")
  message(STATUS "mmc3.pins: 12 ROM lines in order")
  return()
elseif(NOT MODE STREQUAL "inventory")
  message(FATAL_ERROR "mmc3_oracle_inventory: unknown MODE ${MODE}")
endif()

file(READ "${table}" text)
if(text MATCHES "\r")
  message(FATAL_ERROR "mmc3.oracle.inventory: oracle.txt has a carriage return; LF endings only")
endif()
file(STRINGS "${table}" rows)
set(seen)
set(unsupported)
foreach(row IN LISTS rows)
  string(REPLACE "\t" ";" cols "${row}")
  list(LENGTH cols n)
  if(NOT n EQUAL 5)
    message(FATAL_ERROR "mmc3.oracle.inventory: not five tab-separated fields: ${row}")
  endif()
  list(GET cols 0 key)
  list(GET cols 1 status)
  list(GET cols 2 code)
  list(GET cols 3 frames)
  list(GET cols 4 hash)
  if(NOT status STREQUAL "pass" AND NOT status STREQUAL "unsupported")
    message(FATAL_ERROR "mmc3.oracle.inventory: ${key}: status ${status} is not pass or unsupported")
  endif()
  if(NOT code MATCHES "^0x[0-9A-F][0-9A-F]$")
    message(FATAL_ERROR "mmc3.oracle.inventory: ${key}: code ${code} is not 0xNN")
  endif()
  if(NOT frames MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "mmc3.oracle.inventory: ${key}: frames ${frames} is not a decimal budget")
  endif()
  if(NOT hash STREQUAL "-")
    message(FATAL_ERROR "mmc3.oracle.inventory: ${key}: the hash field is not -")
  endif()
  if(status STREQUAL "pass" AND NOT code STREQUAL "0x00")
    message(FATAL_ERROR "mmc3.oracle.inventory: ${key}: a pass row must expect 0x00")
  endif()
  if(status STREQUAL "unsupported")
    if(code STREQUAL "0x00")
      message(FATAL_ERROR "mmc3.oracle.inventory: ${key}: an unsupported row must record its failure code")
    endif()
    list(APPEND unsupported "${key}")
  endif()
  list(APPEND seen "${key}")
endforeach()

if(NOT "${seen}" STREQUAL "${pinned_keys}")
  message(FATAL_ERROR "mmc3.oracle.inventory: the keys of oracle.txt differ from the pins, in order\n  oracle: ${seen}\n  pins:   ${pinned_keys}")
endif()
list(SORT unsupported)
set(want ${nec_keys})
list(SORT want)
if(NOT "${unsupported}" STREQUAL "${want}")
  message(FATAL_ERROR "mmc3.oracle.inventory: the unsupported rows must be exactly the two NEC-revision ROMs ${nec_keys}; found: ${unsupported}")
endif()
message(STATUS "mmc3.oracle.inventory: 12 rows, 10 pass, 2 unsupported")
