cmake_minimum_required(VERSION 3.25)

function(check_nightly_policy workflow out_error)
  # Ignore YAML and shell comments so documentation cannot satisfy a policy.
  string(REPLACE "\r\n" "\n" workflow "${workflow}")
  string(REPLACE "\n" ";" lines "${workflow}")
  set(active)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" trimmed)
    if(trimmed MATCHES "^#" OR trimmed STREQUAL "")
      continue()
    endif()
    string(FIND "${line}" "#" comment_start)
    if(comment_start GREATER_EQUAL 0)
      string(SUBSTRING "${line}" 0 ${comment_start} line)
    endif()
    list(APPEND active "${line}")
  endforeach()
  string(JOIN "\n" code ${active})
  string(FIND "${code}" "  vectors-full:" vectors_start)
  string(FIND "${code}" "  report:" report_start)
  if(vectors_start GREATER_EQUAL 0 AND report_start GREATER vectors_start)
    math(EXPR vectors_length "${report_start} - ${vectors_start}")
    string(SUBSTRING "${code}" ${vectors_start} ${vectors_length} vectors_job)
  else()
    set(vectors_job "")
  endif()
  if(report_start GREATER_EQUAL 0)
    string(SUBSTRING "${code}" ${report_start} -1 report_job)
  else()
    set(report_job "")
  endif()
  foreach(job IN ITEMS vectors-full report)
    set(in_job FALSE)
    set(in_permissions FALSE)
    set(job_permissions)
    foreach(line IN LISTS lines)
      if(line STREQUAL "  ${job}:")
        set(in_job TRUE)
        continue()
      endif()
      if(in_job AND line MATCHES "^  [A-Za-z0-9_-]+:")
        set(in_job FALSE)
        set(in_permissions FALSE)
      endif()
      if(in_job AND line STREQUAL "    permissions:")
        set(in_permissions TRUE)
        continue()
      endif()
      if(in_permissions AND line MATCHES "^    [^ ]")
        set(in_permissions FALSE)
      endif()
      if(in_permissions AND line MATCHES "^      [^ ]+:")
        list(APPEND job_permissions "${line}")
      endif()
    endforeach()
    if(job STREQUAL "vectors-full")
      set(expected_permissions "      contents: read")
    else()
      set(expected_permissions "      issues: write")
    endif()
    if(NOT job_permissions STREQUAL expected_permissions)
      set(${out_error} ".github/workflows/nightly.yml: ${job}-permissions: job permissions must be exactly ${expected_permissions}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  if(NOT code MATCHES "run: cmake --workflow --preset vectors-full")
    set(${out_error} ".github/workflows/nightly.yml: run-preset: vectors-full workflow command is required" PARENT_SCOPE)
    return()
  endif()
  string(FIND "${code}" "cmake --preset vectors-full" configure_index)
  string(FIND "${code}" "ctest --test-dir build/vectors-full --show-only=json-v1" inventory_index)
  string(FIND "${code}" "FULL_ONLY=ON" registration_index)
  string(FIND "${code}" "cmake --workflow --preset vectors-full" workflow_index)
  if(configure_index LESS 0 OR inventory_index LESS configure_index OR
     registration_index LESS inventory_index OR workflow_index LESS registration_index)
    set(${out_error} ".github/workflows/nightly.yml: inventory-order: saved 258-test inventory must pass before the full workflow runs" PARENT_SCOPE)
    return()
  endif()
  string(FIND "${code}" "push:\n    branches: [main]" main_push)
  if(main_push LESS 0)
    set(${out_error} ".github/workflows/nightly.yml: main-push: an unfiltered push to main is required" PARENT_SCOPE)
    return()
  endif()
  if(NOT code MATCHES "permissions: \\{\\}")
    set(${out_error} ".github/workflows/nightly.yml: root-permissions: root permissions must be empty" PARENT_SCOPE)
    return()
  endif()
  string(FIND "${code}" "actions/checkout@" checkout_start)
  string(FIND "${code}" "persist-credentials: false" checkout_persist)
  if(checkout_start LESS 0 OR checkout_persist LESS checkout_start)
    set(${out_error} ".github/workflows/nightly.yml: checkout-credentials: checkout must disable credential persistence" PARENT_SCOPE)
    return()
  endif()
  if(NOT report_job MATCHES "      issues: write")
    set(${out_error} ".github/workflows/nightly.yml: report-permissions: issue writes must be limited to report" PARENT_SCOPE)
    return()
  endif()
  if(report_job MATCHES "actions/checkout@")
    set(${out_error} ".github/workflows/nightly.yml: report-checkout: issue reporter must not check out code" PARENT_SCOPE)
    return()
  endif()
  string(REGEX MATCHALL "issues: write" issue_permissions "${code}")
  list(LENGTH issue_permissions issue_permission_count)
  if(NOT issue_permission_count EQUAL 1)
    set(${out_error} ".github/workflows/nightly.yml: report-permissions: issues: write must appear only once" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "(^|\n)[ \t]+(contents|actions|checks|pull-requests|statuses|id-token|deployments): write")
    set(${out_error} ".github/workflows/nightly.yml: least-privilege: unexpected write permission" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "actions/cache|restore-keys:|cache-hit|(^|\n)[ \t]+cache:")
    set(${out_error} ".github/workflows/nightly.yml: no-cache: cache and restore steps are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "SKIP_RETURN_CODE|RETURN_CODE[ \t]+77|EXIT[ \t]+77|exit[ \t]+77|continue-on-error:[ \t]*true|\\|\\|[ \t]*true")
    set(${out_error} ".github/workflows/nightly.yml: no-skip: skipped or failure-suppressing results are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "secrets\\.|\\$\\{\\{[ \t]*secrets")
    set(${out_error} ".github/workflows/nightly.yml: no-secrets: secrets are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "(^|[ /])(git[ \t]+commit|git[ \t]+push|gh[ \t]+repo[ \t]+sync)([ \t]|$)")
    set(${out_error} ".github/workflows/nightly.yml: no-writeback: commits and pushes are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "pull_request_target:|workflow_run:")
    set(${out_error} ".github/workflows/nightly.yml: trusted-triggers: privileged triggers are forbidden" PARENT_SCOPE)
    return()
  endif()
  string(FIND "${code}" "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" upload_index)
  string(FIND "${code}" "name: Verify run evidence" evidence_index)
  string(FIND "${code}" "test -s build/vectors-full/registered-tests.json" inventory_evidence)
  string(FIND "${code}" "test -s build/vectors-full/vectors-full.junit.xml" junit_evidence)
  if(upload_index LESS 0 OR evidence_index LESS 0 OR inventory_evidence LESS 0 OR
     junit_evidence LESS 0 OR NOT code MATCHES "if-no-files-found: error")
    set(${out_error} ".github/workflows/nightly.yml: run-evidence: pinned artifact upload and fail-closed evidence checks are required" PARENT_SCOPE)
    return()
  endif()
  string(SUBSTRING "${code}" ${evidence_index} 180 evidence_step)
  string(SUBSTRING "${code}" ${upload_index} 180 upload_step)
  if(NOT evidence_step MATCHES "if: always\(\)" OR NOT upload_step MATCHES "if: always\(\)")
    set(${out_error} ".github/workflows/nightly.yml: run-evidence: evidence checks and artifact upload must run after success or failure" PARENT_SCOPE)
    return()
  endif()
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(clean_fixture out_text)
  set(text "# cache: actions/cache is only a comment.\nname: Nightly\non:\n  schedule:\n    - cron: \"17 4 * * *\"\npermissions: {}\njobs:\n  vectors-full:\n    permissions:\n      contents: read\n    steps:\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1\n        with:\n          persist-credentials: false\n      - run: cmake --workflow --preset vectors-full\n  report:\n    permissions:\n      issues: write\n")
  string(REPLACE "permissions: {}" "  push:\n    branches: [main]\npermissions: {}" text "${text}")
  string(REPLACE "      - run: cmake --workflow --preset vectors-full\n" "      - run: cmake --preset vectors-full\n      - run: ctest --test-dir build/vectors-full --show-only=json-v1\n      - run: cmake -DFULL_ONLY=ON -P tests/cmake/vector_registration_policy.cmake\n      - run: cmake --workflow --preset vectors-full\n" text "${text}")
  set(evidence "      - name: Verify run evidence\n        if: always()\n        run: |\n          test -s build/vectors-full/registered-tests.json\n          test -s build/vectors-full/vectors-full.junit.xml\n      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a\n        if: always()\n        with:\n          if-no-files-found: error\n")
  string(REPLACE "  report:" "${evidence}  report:" text "${text}")
  set(${out_text} "${text}" PARENT_SCOPE)
endfunction()

if(SELFTEST)
  clean_fixture(clean)
  check_nightly_policy("${clean}" error)
  if(error)
    message(FATAL_ERROR "clean workflow fixture failed: ${error}")
  endif()
  foreach(mutation cache skip permission privileged)
    set(mutated "${clean}")
    if(mutation STREQUAL cache)
      string(APPEND mutated "      - uses: actions/cache@0123456789012345678901234567890123456789\n")
    elseif(mutation STREQUAL skip)
      string(APPEND mutated "      - run: ctest --preset vectors-full --output-on-failure\n        env:\n          SKIP_RETURN_CODE: 77\n")
    elseif(mutation STREQUAL permission)
      string(REPLACE "      contents: read" "      contents: write" mutated "${mutated}")
    elseif(mutation STREQUAL privileged)
      string(APPEND mutated "  pull_request_target:\n")
    endif()
    check_nightly_policy("${mutated}" error)
    if(NOT error)
      message(FATAL_ERROR "nightly policy self-test did not detect ${mutation}")
    endif()
  endforeach()
  message(STATUS "nightly workflow policy self-test passed")
elseif(DEFINED WORKFLOW)
  file(READ "${WORKFLOW}" workflow)
  check_nightly_policy("${workflow}" error)
  if(error)
    message(FATAL_ERROR "${error}")
  endif()
  if(DEFINED ROOT)
    file(READ "${ROOT}/CMakePresets.json" presets)
    string(JSON preset_count LENGTH "${presets}" testPresets)
    set(junit_path "")
    set(no_tests_action "")
    set(full_label "")
    if(preset_count GREATER 0)
      math(EXPR preset_last "${preset_count} - 1")
      foreach(index RANGE 0 ${preset_last})
        string(JSON preset_name GET "${presets}" testPresets ${index} name)
        if(preset_name STREQUAL "vectors-full")
          string(JSON junit_path GET "${presets}" testPresets ${index} output outputJUnitFile)
          string(JSON no_tests_action GET "${presets}" testPresets ${index} execution noTestsAction)
          string(JSON full_label GET "${presets}" testPresets ${index} filter include label)
        endif()
      endforeach()
    endif()
    set(expected_junit "\${sourceDir}/build/vectors-full/vectors-full.junit.xml")
    if(NOT junit_path STREQUAL expected_junit)
      message(FATAL_ERROR "CMakePresets.json: junit-output: vectors-full needs a stable JUnit path in build/vectors-full")
    endif()
    if(NOT no_tests_action STREQUAL "error" OR NOT full_label STREQUAL "vectors-full")
      message(FATAL_ERROR "CMakePresets.json: full-filter: vectors-full must select the full label and fail on an empty inventory")
    endif()
    foreach(relative IN ITEMS
        CMakePresets.json
        tests/cmake/fetch_vectors.cmake
        tests/cmake/vectors_full_run.cmake
        tests/cmake/vectors_sample_match.cmake)
      file(READ "${ROOT}/${relative}" source)
      string(REGEX REPLACE "(^|\n)[ \t]*#[^\n]*" "" source "${source}")
      string(REGEX REPLACE "#[^\n]*" "" source "${source}")
      if(source MATCHES "SKIP_RETURN_CODE|RETURN_CODE[ \t]+77|EXIT[ \t]+77|exit[ \t]+77")
        message(FATAL_ERROR "${relative}: no-skip: skip code 77 is forbidden in the full-vector tier")
      endif()
    endforeach()
  endif()
  message(STATUS "nightly workflow policy passed")
else()
  message(FATAL_ERROR "WORKFLOW is required")
endif()
