cmake_minimum_required(VERSION 3.25)

function(check_nightly_policy workflow out_error)
  # Ignore YAML and shell comments so documentation cannot satisfy a policy.
  string(REPLACE "\r\n" "\n" workflow "${workflow}")
  string(REPLACE "\n" ";" lines "${workflow}")
  set(active)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" trimmed)
    if(trimmed MATCHES "^#" OR trimmed STREQUAL "")
      continue()
    endif()
    string(FIND "${line}" "#" comment_start)
    if(comment_start GREATER_EQUAL 0)
      string(SUBSTRING "${line}" 0 ${comment_start} line)
    endif()
    list(APPEND active "${line}")
  endforeach()
  string(JOIN "\n" code ${active})
  string(FIND "${code}" "  vectors-full:" vectors_start)
  string(FIND "${code}" "  report:" report_start)
  if(vectors_start GREATER_EQUAL 0 AND report_start GREATER vectors_start)
    math(EXPR vectors_length "${report_start} - ${vectors_start}")
    string(SUBSTRING "${code}" ${vectors_start} ${vectors_length} vectors_job)
  else()
    set(vectors_job "")
  endif()
  if(report_start GREATER_EQUAL 0)
    string(SUBSTRING "${code}" ${report_start} -1 report_job)
  else()
    set(report_job "")
  endif()
  if(NOT code MATCHES "run: cmake --workflow --preset vectors-full")
    set(${out_error} ".github/workflows/nightly.yml: run-preset: vectors-full workflow command is required" PARENT_SCOPE)
    return()
  endif()
  if(NOT code MATCHES "permissions: \\{\\}")
    set(${out_error} ".github/workflows/nightly.yml: root-permissions: root permissions must be empty" PARENT_SCOPE)
    return()
  endif()
  if(NOT vectors_job MATCHES "      contents: read" OR vectors_job MATCHES "      issues: write" OR vectors_job MATCHES "      contents: write")
    set(${out_error} ".github/workflows/nightly.yml: vectors-permissions: vectors-full must have contents: read only" PARENT_SCOPE)
    return()
  endif()
  string(FIND "${code}" "actions/checkout@" checkout_start)
  string(FIND "${code}" "persist-credentials: false" checkout_persist)
  if(checkout_start LESS 0 OR checkout_persist LESS checkout_start)
    set(${out_error} ".github/workflows/nightly.yml: checkout-credentials: checkout must disable credential persistence" PARENT_SCOPE)
    return()
  endif()
  if(NOT report_job MATCHES "      issues: write")
    set(${out_error} ".github/workflows/nightly.yml: report-permissions: issue writes must be limited to report" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "(^|\n)[ \t]+(contents|actions|checks|pull-requests|statuses|id-token|deployments): write")
    set(${out_error} ".github/workflows/nightly.yml: least-privilege: unexpected write permission" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "actions/cache|restore-keys:|cache-hit")
    set(${out_error} ".github/workflows/nightly.yml: no-cache: cache and restore steps are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "SKIP_RETURN_CODE|RETURN_CODE[ \t]+77|EXIT[ \t]+77|exit[ \t]+77|continue-on-error:[ \t]*true|\\|\\|[ \t]*true")
    set(${out_error} ".github/workflows/nightly.yml: no-skip: skipped or failure-suppressing results are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "secrets\\.|\\$\\{\\{[ \t]*secrets")
    set(${out_error} ".github/workflows/nightly.yml: no-secrets: secrets are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "(^|[ /])(git[ \t]+commit|git[ \t]+push|gh[ \t]+repo[ \t]+sync)([ \t]|$)")
    set(${out_error} ".github/workflows/nightly.yml: no-writeback: commits and pushes are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "pull_request_target:|workflow_run:")
    set(${out_error} ".github/workflows/nightly.yml: trusted-triggers: privileged triggers are forbidden" PARENT_SCOPE)
    return()
  endif()
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(clean_fixture out_text)
  set(text "# cache: actions/cache is only a comment.\nname: Nightly\non:\n  schedule:\n    - cron: \"17 4 * * *\"\npermissions: {}\njobs:\n  vectors-full:\n    permissions:\n      contents: read\n    steps:\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1\n        with:\n          persist-credentials: false\n      - run: cmake --workflow --preset vectors-full\n  report:\n    permissions:\n      issues: write\n")
  set(${out_text} "${text}" PARENT_SCOPE)
endfunction()

if(SELFTEST)
  clean_fixture(clean)
  check_nightly_policy("${clean}" error)
  if(error)
    message(FATAL_ERROR "clean workflow fixture failed: ${error}")
  endif()
  foreach(mutation cache skip permission privileged)
    set(mutated "${clean}")
    if(mutation STREQUAL cache)
      string(APPEND mutated "      - uses: actions/cache@0123456789012345678901234567890123456789\n")
    elseif(mutation STREQUAL skip)
      string(APPEND mutated "      - run: ctest --preset vectors-full --output-on-failure\n        env:\n          SKIP_RETURN_CODE: 77\n")
    elseif(mutation STREQUAL permission)
      string(REPLACE "      contents: read" "      contents: write" mutated "${mutated}")
    elseif(mutation STREQUAL privileged)
      string(APPEND mutated "  pull_request_target:\n")
    endif()
    check_nightly_policy("${mutated}" error)
    if(NOT error)
      message(FATAL_ERROR "nightly policy self-test did not detect ${mutation}")
    endif()
  endforeach()
  message(STATUS "nightly workflow policy self-test passed")
elseif(DEFINED WORKFLOW)
  file(READ "${WORKFLOW}" workflow)
  check_nightly_policy("${workflow}" error)
  if(error)
    message(FATAL_ERROR "${error}")
  endif()
  if(DEFINED ROOT)
    foreach(relative IN ITEMS
        CMakePresets.json
        tests/cmake/fetch_vectors.cmake
        tests/cmake/vectors_full_run.cmake
        tests/cmake/vectors_sample_match.cmake)
      file(READ "${ROOT}/${relative}" source)
      if(source MATCHES "SKIP_RETURN_CODE|RETURN_CODE[ \t]+77|EXIT[ \t]+77|exit[ \t]+77")
        message(FATAL_ERROR "${relative}: no-skip: skip code 77 is forbidden in the full-vector tier")
      endif()
    endforeach()
  endif()
  message(STATUS "nightly workflow policy passed")
else()
  message(FATAL_ERROR "WORKFLOW is required")
endif()
