cmake_minimum_required(VERSION 3.25)

function(check_nightly_policy workflow out_error)
  # Ignore YAML and shell comments so documentation cannot satisfy a policy.
  string(REPLACE "\r\n" "\n" workflow "${workflow}")
  string(REPLACE "\n" ";" lines "${workflow}")
  set(active)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" trimmed)
    if(trimmed MATCHES "^#" OR trimmed STREQUAL "")
      continue()
    endif()
    string(FIND "${line}" "#" comment_start)
    if(comment_start GREATER_EQUAL 0)
      string(SUBSTRING "${line}" 0 ${comment_start} line)
    endif()
    list(APPEND active "${line}")
  endforeach()
  string(JOIN "\n" code ${active})
  # Each lane is checked on its own text: from its two-space job header to the
  # next two-space job header, so a step in one lane cannot satisfy another.
  set(lanes vectors-full mmc3-oracle)
  set(report_job "")
  foreach(job IN LISTS lanes ITEMS report)
    set(job_text "")
    set(in_job FALSE)
    foreach(line IN LISTS active)
      if(line MATCHES "^  [A-Za-z0-9_-]+:")
        if(line STREQUAL "  ${job}:")
          set(in_job TRUE)
        else()
          set(in_job FALSE)
        endif()
      endif()
      if(in_job)
        string(APPEND job_text "${line}\n")
      endif()
    endforeach()
    set(job_text_${job} "${job_text}")
    if(job STREQUAL "report")
      set(report_job "${job_text}")
    endif()
  endforeach()
  foreach(job IN LISTS lanes ITEMS report)
    set(in_job FALSE)
    set(in_permissions FALSE)
    set(job_permissions)
    foreach(line IN LISTS lines)
      if(line STREQUAL "  ${job}:")
        set(in_job TRUE)
        continue()
      endif()
      if(in_job AND line MATCHES "^  [A-Za-z0-9_-]+:")
        set(in_job FALSE)
        set(in_permissions FALSE)
      endif()
      if(in_job AND line STREQUAL "    permissions:")
        set(in_permissions TRUE)
        continue()
      endif()
      if(in_permissions AND line MATCHES "^    [^ ]")
        set(in_permissions FALSE)
      endif()
      if(in_permissions AND line MATCHES "^      [^ ]+:")
        list(APPEND job_permissions "${line}")
      endif()
    endforeach()
    if(job STREQUAL "report")
      set(expected_permissions "      issues: write")
    else()
      set(expected_permissions "      contents: read")
    endif()
    if(NOT job_permissions STREQUAL expected_permissions)
      set(${out_error} ".github/workflows/nightly.yml: ${job}-permissions: job permissions must be exactly ${expected_permissions}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(lane IN LISTS lanes)
    set(lane_job "${job_text_${lane}}")
    if(NOT lane_job MATCHES "run: cmake --workflow --preset ${lane}\n")
      set(${out_error} ".github/workflows/nightly.yml: run-preset: ${lane} workflow command is required" PARENT_SCOPE)
      return()
    endif()
    string(FIND "${lane_job}" "cmake --preset ${lane}\n" configure_index)
    string(FIND "${lane_job}" "ctest --test-dir build/${lane} --show-only=json-v1" inventory_index)
    string(FIND "${lane_job}" "cmake --workflow --preset ${lane}" workflow_index)
    set(registration_index ${inventory_index})
    if(lane STREQUAL "vectors-full")
      string(FIND "${lane_job}" "FULL_ONLY=ON" registration_index)
      if(registration_index LESS 0)
        set(registration_index -1)
      endif()
    endif()
    if(configure_index LESS 0 OR inventory_index LESS configure_index OR
       registration_index LESS inventory_index OR workflow_index LESS registration_index)
      set(${out_error} ".github/workflows/nightly.yml: inventory-order: ${lane} saved inventory must pass before its full workflow runs" PARENT_SCOPE)
      return()
    endif()
    string(FIND "${lane_job}" "actions/checkout@" lane_checkout)
    string(FIND "${lane_job}" "persist-credentials: false" lane_persist)
    if(lane_checkout LESS 0 OR lane_persist LESS lane_checkout)
      set(${out_error} ".github/workflows/nightly.yml: checkout-credentials: ${lane} checkout must disable credential persistence" PARENT_SCOPE)
      return()
    endif()
    string(FIND "${lane_job}" "actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9" upload_index)
    string(FIND "${lane_job}" "name: Verify run evidence" evidence_index)
    string(FIND "${lane_job}" "test -s build/${lane}/registered-tests.json" inventory_evidence)
    string(FIND "${lane_job}" "test -s build/${lane}/${lane}.junit.xml" junit_evidence)
    if(upload_index LESS 0 OR evidence_index LESS 0 OR inventory_evidence LESS 0 OR
       junit_evidence LESS 0 OR NOT lane_job MATCHES "if-no-files-found: error")
      set(${out_error} ".github/workflows/nightly.yml: run-evidence: ${lane} needs a pinned artifact upload and fail-closed evidence checks" PARENT_SCOPE)
      return()
    endif()
    string(SUBSTRING "${lane_job}" ${evidence_index} 180 evidence_step)
    string(SUBSTRING "${lane_job}" ${upload_index} 180 upload_step)
    if(NOT evidence_step MATCHES "if: always\\(\\)" OR NOT upload_step MATCHES "if: always\\(\\)")
      set(${out_error} ".github/workflows/nightly.yml: run-evidence: ${lane} evidence checks and artifact upload must run after success or failure" PARENT_SCOPE)
      return()
    endif()
    if(NOT report_job MATCHES "needs:[^\n]*[\\[ ,]${lane}[],]")
      set(${out_error} ".github/workflows/nightly.yml: report-needs: report must need ${lane}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  string(FIND "${code}" "push:\n    branches: [main]" main_push)
  if(main_push LESS 0)
    set(${out_error} ".github/workflows/nightly.yml: main-push: an unfiltered push to main is required" PARENT_SCOPE)
    return()
  endif()
  if(NOT code MATCHES "permissions: \\{\\}")
    set(${out_error} ".github/workflows/nightly.yml: root-permissions: root permissions must be empty" PARENT_SCOPE)
    return()
  endif()
  if(NOT report_job MATCHES "      issues: write")
    set(${out_error} ".github/workflows/nightly.yml: report-permissions: issue writes must be limited to report" PARENT_SCOPE)
    return()
  endif()
  if(report_job MATCHES "actions/checkout@")
    set(${out_error} ".github/workflows/nightly.yml: report-checkout: issue reporter must not check out code" PARENT_SCOPE)
    return()
  endif()
  string(REGEX MATCHALL "issues: write" issue_permissions "${code}")
  list(LENGTH issue_permissions issue_permission_count)
  if(NOT issue_permission_count EQUAL 1)
    set(${out_error} ".github/workflows/nightly.yml: report-permissions: issues: write must appear only once" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "(^|\n)[ \t]+(contents|actions|checks|pull-requests|statuses|id-token|deployments): write")
    set(${out_error} ".github/workflows/nightly.yml: least-privilege: unexpected write permission" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "actions/cache|restore-keys:|cache-hit|(^|\n)[ \t]+cache:")
    set(${out_error} ".github/workflows/nightly.yml: no-cache: cache and restore steps are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "SKIP_RETURN_CODE|RETURN_CODE[ \t]+77|EXIT[ \t]+77|exit[ \t]+77|continue-on-error:[ \t]*true|\\|\\|[ \t]*true")
    set(${out_error} ".github/workflows/nightly.yml: no-skip: skipped or failure-suppressing results are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "secrets\\.|\\$\\{\\{[ \t]*secrets")
    set(${out_error} ".github/workflows/nightly.yml: no-secrets: secrets are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "(^|[ /])(git[ \t]+commit|git[ \t]+push|gh[ \t]+repo[ \t]+sync)([ \t]|$)")
    set(${out_error} ".github/workflows/nightly.yml: no-writeback: commits and pushes are forbidden" PARENT_SCOPE)
    return()
  endif()
  if(code MATCHES "pull_request_target:|workflow_run:")
    set(${out_error} ".github/workflows/nightly.yml: trusted-triggers: privileged triggers are forbidden" PARENT_SCOPE)
    return()
  endif()
  set(${out_error} "" PARENT_SCOPE)
endfunction()

# One lane's minimal clean job text: inventory before the workflow command,
# then the evidence step and the pinned upload.
function(lane_fixture lane registration out_text)
  set(text "  ${lane}:\n    permissions:\n      contents: read\n    steps:\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1\n        with:\n          persist-credentials: false\n      - run: cmake --preset ${lane}\n      - run: ctest --test-dir build/${lane} --show-only=json-v1\n${registration}      - run: cmake --workflow --preset ${lane}\n      - name: Verify run evidence\n        if: always()\n        run: |\n          test -s build/${lane}/registered-tests.json\n          test -s build/${lane}/${lane}.junit.xml\n      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9\n        if: always()\n        with:\n          if-no-files-found: error\n")
  set(${out_text} "${text}" PARENT_SCOPE)
endfunction()

function(clean_fixture out_text)
  set(text "# cache: actions/cache is only a comment.\nname: Nightly\non:\n  schedule:\n    - cron: \"17 4 * * *\"\n  push:\n    branches: [main]\npermissions: {}\njobs:\n")
  lane_fixture(vectors-full "      - run: cmake -DFULL_ONLY=ON -P tests/cmake/vector_registration_policy.cmake\n" vectors)
  lane_fixture(mmc3-oracle "" mmc3)
  string(APPEND text "${vectors}${mmc3}  report:\n    needs: [vectors-full, mmc3-oracle]\n    permissions:\n      issues: write\n")
  set(${out_text} "${text}" PARENT_SCOPE)
endfunction()

# Applies a REPLACE only from the mmc3-oracle job header onward, so a mutation
# lands on that lane alone and the policy must catch it there.
function(mutate_mmc3 text from to out_text)
  string(FIND "${text}" "  mmc3-oracle:\n" start)
  string(SUBSTRING "${text}" 0 ${start} head)
  string(SUBSTRING "${text}" ${start} -1 tail)
  string(REPLACE "${from}" "${to}" tail "${tail}")
  set(${out_text} "${head}${tail}" PARENT_SCOPE)
endfunction()

if(SELFTEST)
  clean_fixture(clean)
  check_nightly_policy("${clean}" error)
  if(error)
    message(FATAL_ERROR "clean workflow fixture failed: ${error}")
  endif()
  set(evidence_step "      - name: Verify run evidence\n        if: always()\n        run: |\n          test -s build/mmc3-oracle/registered-tests.json\n          test -s build/mmc3-oracle/mmc3-oracle.junit.xml\n")
  set(workflow_step "      - run: cmake --workflow --preset mmc3-oracle\n")
  foreach(mutation cache skip permission privileged
      mmc3-evidence mmc3-write mmc3-skip mmc3-needs mmc3-order)
    set(mutated "${clean}")
    if(mutation STREQUAL cache)
      string(APPEND mutated "      - uses: actions/cache@0123456789012345678901234567890123456789\n")
    elseif(mutation STREQUAL skip)
      string(APPEND mutated "      - run: ctest --preset vectors-full --output-on-failure\n        env:\n          SKIP_RETURN_CODE: 77\n")
    elseif(mutation STREQUAL permission)
      string(REPLACE "      contents: read" "      contents: write" mutated "${mutated}")
    elseif(mutation STREQUAL privileged)
      string(APPEND mutated "  pull_request_target:\n")
    elseif(mutation STREQUAL mmc3-evidence)
      mutate_mmc3("${mutated}" "${evidence_step}" "" mutated)
    elseif(mutation STREQUAL mmc3-write)
      mutate_mmc3("${mutated}" "      contents: read" "      contents: write" mutated)
    elseif(mutation STREQUAL mmc3-skip)
      mutate_mmc3("${mutated}" "${workflow_step}" "${workflow_step}        env:\n          SKIP_RETURN_CODE: 77\n" mutated)
    elseif(mutation STREQUAL mmc3-needs)
      string(REPLACE "needs: [vectors-full, mmc3-oracle]" "needs: [vectors-full]" mutated "${mutated}")
    elseif(mutation STREQUAL mmc3-order)
      mutate_mmc3("${mutated}" "      - run: cmake --preset mmc3-oracle\n" "${workflow_step}      - run: cmake --preset mmc3-oracle\n" mutated)
    endif()
    if(mutated STREQUAL clean)
      message(FATAL_ERROR "nightly policy self-test mutation ${mutation} changed nothing")
    endif()
    check_nightly_policy("${mutated}" error)
    if(NOT error)
      message(FATAL_ERROR "nightly policy self-test did not detect ${mutation}")
    endif()
  endforeach()
  message(STATUS "nightly workflow policy self-test passed")
elseif(DEFINED WORKFLOW)
  file(READ "${WORKFLOW}" workflow)
  check_nightly_policy("${workflow}" error)
  if(error)
    message(FATAL_ERROR "${error}")
  endif()
  if(DEFINED ROOT)
    file(READ "${ROOT}/CMakePresets.json" presets)
    string(JSON preset_count LENGTH "${presets}" testPresets)
    foreach(lane IN ITEMS vectors-full mmc3-oracle)
      set(junit_path "")
      set(no_tests_action "")
      set(lane_label "")
      if(preset_count GREATER 0)
        math(EXPR preset_last "${preset_count} - 1")
        foreach(index RANGE 0 ${preset_last})
          string(JSON preset_name GET "${presets}" testPresets ${index} name)
          if(preset_name STREQUAL "${lane}")
            string(JSON junit_path GET "${presets}" testPresets ${index} output outputJUnitFile)
            string(JSON no_tests_action GET "${presets}" testPresets ${index} execution noTestsAction)
            string(JSON lane_label GET "${presets}" testPresets ${index} filter include label)
          endif()
        endforeach()
      endif()
      set(expected_junit "\${sourceDir}/build/${lane}/${lane}.junit.xml")
      if(NOT junit_path STREQUAL expected_junit)
        message(FATAL_ERROR "CMakePresets.json: junit-output: ${lane} needs a stable JUnit path in build/${lane}")
      endif()
      if(NOT no_tests_action STREQUAL "error" OR NOT lane_label STREQUAL "${lane}")
        message(FATAL_ERROR "CMakePresets.json: full-filter: ${lane} must select its own label and fail on an empty inventory")
      endif()
    endforeach()
    foreach(relative IN ITEMS
        CMakePresets.json
        tests/cmake/fetch_vectors.cmake
        tests/cmake/vectors_full_run.cmake
        tests/cmake/vectors_sample_match.cmake
        tests/cmake/fetch_blargg_mmc3.cmake
        tests/cmake/mmc3_oracle_run.cmake)
      file(READ "${ROOT}/${relative}" source)
      string(REGEX REPLACE "(^|\n)[ \t]*#[^\n]*" "" source "${source}")
      string(REGEX REPLACE "#[^\n]*" "" source "${source}")
      if(source MATCHES "SKIP_RETURN_CODE|RETURN_CODE[ \t]+77|EXIT[ \t]+77|exit[ \t]+77")
        message(FATAL_ERROR "${relative}: no-skip: skip code 77 is forbidden in the nightly lanes")
      endif()
    endforeach()
  endif()
  message(STATUS "nightly workflow policy passed")
else()
  message(FATAL_ERROR "WORKFLOW is required")
endif()
