# Checks tests/vectors/pins.txt offline (D-20): the pin line's exact format,
# then exactly 256 lines "<sha256>  nes6502/v1/<xx>.json  <size>" in path
# order 00 to ff, sizes summing to 1081529097 (the upstream tree), and the
# pin's commit equal to the manifest pin of tests/vectors/65x02-sample.n65v,
# so the sample and the full set come from one commit.
#
#   cmake -DSOURCE_DIR=<repo> -P pins_check.cmake
#   cmake -DSOURCE_DIR=<repo> -DSELFTEST=ON -DWORK=<dir> -P pins_check.cmake
#
# SELFTEST checks a copy with lines 2 and 3 swapped and passes only if the
# check reports it as not sorted.

cmake_minimum_required(VERSION 3.25)

if(NOT SOURCE_DIR)
  message(FATAL_ERROR "pins_check: SOURCE_DIR is required")
endif()
set(sub "nes6502/v1")
set(pins_rel "tests/vectors/pins.txt")
set(manifest "${SOURCE_DIR}/tests/roms/manifest.txt")

# Sets OUT to the first problem found in PINS, or to nothing.
function(pins_check pins out)
  set(${out} "" PARENT_SCOPE)
  file(READ "${pins}" text)
  if(text MATCHES "\r")
    set(${out} "pins.txt has a carriage return; LF endings only" PARENT_SCOPE)
    return()
  endif()
  if(NOT text MATCHES "\n$")
    set(${out} "pins.txt does not end with a newline" PARENT_SCOPE)
    return()
  endif()
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" lines "${text}")
  list(LENGTH lines n)
  if(NOT n EQUAL 257)
    math(EXPR n "${n} - 1")
    set(${out} "pins.txt has ${n} file lines, expected 256" PARENT_SCOPE)
    return()
  endif()
  list(GET lines 0 head)
  if(NOT head MATCHES "^repo https://github\\.com/SingleStepTests/65x02 commit ([0-9a-f]+) path ${sub} licence MIT$")
    set(${out} "pins.txt line 1 is not 'repo https://github.com/SingleStepTests/65x02 commit <sha> path ${sub} licence MIT'" PARENT_SCOPE)
    return()
  endif()
  set(commit "${CMAKE_MATCH_1}")
  string(LENGTH "${commit}" len)
  if(NOT len EQUAL 40)
    set(${out} "pins.txt line 1: commit is not 40 hex digits" PARENT_SCOPE)
    return()
  endif()

  set(names)
  foreach(h 0 1 2 3 4 5 6 7 8 9 a b c d e f)
    foreach(l 0 1 2 3 4 5 6 7 8 9 a b c d e f)
      list(APPEND names ${h}${l})
    endforeach()
  endforeach()
  set(total 0)
  foreach(i RANGE 1 256)
    list(GET lines ${i} line)
    math(EXPR lineno "${i} + 1")
    if(NOT line MATCHES "^([0-9a-f]+)  ${sub}/([0-9a-f][0-9a-f])\\.json  ([0-9]+)$")
      set(${out} "pins.txt line ${lineno} is not '<sha256>  ${sub}/<xx>.json  <size>'" PARENT_SCOPE)
      return()
    endif()
    set(sha "${CMAKE_MATCH_1}")
    set(xx "${CMAKE_MATCH_2}")
    set(size "${CMAKE_MATCH_3}")
    string(LENGTH "${sha}" len)
    if(NOT len EQUAL 64)
      set(${out} "pins.txt line ${lineno}: sha256 is not 64 hex digits" PARENT_SCOPE)
      return()
    endif()
    math(EXPR k "${i} - 1")
    list(GET names ${k} want)
    if(NOT xx STREQUAL want)
      set(${out} "pins.txt line ${lineno}: ${sub}/${xx}.json where ${sub}/${want}.json belongs: not sorted" PARENT_SCOPE)
      return()
    endif()
    math(EXPR total "${total} + ${size}")
  endforeach()
  if(NOT total EQUAL 1081529097)
    set(${out} "pins.txt sizes sum to ${total}, expected 1081529097" PARENT_SCOPE)
    return()
  endif()

  file(STRINGS "${manifest}" mlines REGEX "^tests/vectors/65x02-sample\\.n65v\t")
  list(LENGTH mlines m)
  if(NOT m EQUAL 1)
    set(${out} "manifest.txt has ${m} lines for tests/vectors/65x02-sample.n65v, expected 1" PARENT_SCOPE)
    return()
  endif()
  string(REPLACE "\t" ";" fields "${mlines}")
  list(GET fields 2 sample_pin)
  if(NOT commit STREQUAL sample_pin)
    set(${out} "pins.txt commit ${commit} differs from the sample's manifest pin ${sample_pin}" PARENT_SCOPE)
  endif()
endfunction()

if(SELFTEST)
  if(NOT WORK)
    message(FATAL_ERROR "pins_check: SELFTEST needs WORK")
  endif()
  file(READ "${SOURCE_DIR}/${pins_rel}" text)
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" lines "${text}")
  list(GET lines 1 a)
  list(GET lines 2 b)
  list(REMOVE_AT lines 1 2)
  list(INSERT lines 1 "${b}" "${a}")
  string(REPLACE ";" "\n" text "${lines}")
  set(copy "${WORK}/pins_check_selftest.txt")
  file(WRITE "${copy}" "${text}\n")
  pins_check("${copy}" found)
  if(NOT found MATCHES "not sorted$")
    message(FATAL_ERROR "self-test: expected a 'not sorted' report, got: '${found}'")
  endif()
  message(STATUS "self-test reported: ${found}")
  return()
endif()

pins_check("${SOURCE_DIR}/${pins_rel}" found)
if(found)
  message(FATAL_ERROR "${found}")
endif()
message(STATUS "pins.txt: 256 files in order, 1081529097 bytes, the sample's commit")
