cmake_minimum_required(VERSION 3.25)

function(expected_names prefix out_var)
  set(names)
  foreach(h 0 1 2 3 4 5 6 7 8 9 a b c d e f)
    foreach(l 0 1 2 3 4 5 6 7 8 9 a b c d e f)
      list(APPEND names "${prefix}${h}${l}")
    endforeach()
  endforeach()
  set(${out_var} "${names}" PARENT_SCOPE)
endfunction()

function(load_inventory build_dir out_json out_error)
  execute_process(COMMAND "${CTEST}" --test-dir "${build_dir}" --show-only=json-v1
    RESULT_VARIABLE status OUTPUT_VARIABLE json ERROR_VARIABLE stderr)
  if(NOT status EQUAL 0)
    set(${out_error} "cannot read CTest inventory from ${build_dir}: ${stderr}" PARENT_SCOPE)
    return()
  endif()
  set(${out_json} "${json}" PARENT_SCOPE)
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(property_contains json test_index wanted_property wanted_value out_found)
  string(JSON property_count LENGTH "${json}" tests ${test_index} properties)
  set(found FALSE)
  if(property_count GREATER 0)
    math(EXPR last_property "${property_count} - 1")
    foreach(property_index RANGE 0 ${last_property})
      string(JSON property_name GET "${json}" tests ${test_index} properties ${property_index} name)
      if(property_name STREQUAL wanted_property)
        string(JSON value_type TYPE "${json}" tests ${test_index} properties ${property_index} value)
        if(value_type STREQUAL ARRAY)
          string(JSON value_count LENGTH "${json}" tests ${test_index} properties ${property_index} value)
          if(value_count GREATER 0)
            math(EXPR last_value "${value_count} - 1")
            foreach(value_index RANGE 0 ${last_value})
              string(JSON value GET "${json}" tests ${test_index} properties ${property_index} value ${value_index})
              if(value STREQUAL wanted_value)
                set(found TRUE)
              endif()
            endforeach()
          endif()
        else()
          string(JSON value GET "${json}" tests ${test_index} properties ${property_index} value)
          if(value STREQUAL wanted_value)
            set(found TRUE)
          endif()
        endif()
      endif()
    endforeach()
  endif()
  set(${out_found} "${found}" PARENT_SCOPE)
endfunction()

function(property_exists json test_index wanted_property out_found)
  string(JSON property_count LENGTH "${json}" tests ${test_index} properties)
  set(found FALSE)
  if(property_count GREATER 0)
    math(EXPR last_property "${property_count} - 1")
    foreach(property_index RANGE 0 ${last_property})
      string(JSON property_name GET "${json}" tests ${test_index} properties ${property_index} name)
      if(property_name STREQUAL wanted_property)
        set(found TRUE)
      endif()
    endforeach()
  endif()
  set(${out_found} "${found}" PARENT_SCOPE)
endfunction()

function(check_ci_inventory json out_error)
  string(JSON count LENGTH "${json}" tests)
  set(actual)
  if(count GREATER 0)
    math(EXPR last_test "${count} - 1")
    foreach(index RANGE 0 ${last_test})
      string(JSON name GET "${json}" tests ${index} name)
      if(name MATCHES "^cpu\\.vectors-full\\.")
        set(${out_error} "ordinary ci inventory contains full-tier test ${name}" PARENT_SCOPE)
        return()
      endif()
      if(name MATCHES "^cpu\\.vectors\\.[0-9a-f][0-9a-f]$")
        list(APPEND actual "${name}")
        property_exists("${json}" ${index} DISABLED disabled)
        property_exists("${json}" ${index} SKIP_RETURN_CODE skip_code)
        if(disabled OR skip_code)
          set(${out_error} "sample opcode registration is disabled or skipped: ${name}" PARENT_SCOPE)
          return()
        endif()
      endif()
    endforeach()
  endif()
  expected_names("cpu.vectors." expected)
  list(SORT actual)
  list(SORT expected)
  if(NOT actual STREQUAL expected)
    set(missing ${expected})
    set(extra ${actual})
    foreach(name IN LISTS actual)
      list(REMOVE_ITEM missing "${name}")
    endforeach()
    foreach(name IN LISTS expected)
      list(REMOVE_ITEM extra "${name}")
    endforeach()
    set(${out_error} "ci opcode inventory mismatch; missing=${missing}; extra=${extra}" PARENT_SCOPE)
    return()
  endif()
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(check_full_inventory json out_error)
  string(JSON count LENGTH "${json}" tests)
  set(actual)
  set(fetch_index -1)
  set(sample_index -1)
  if(count GREATER 0)
    math(EXPR last_test "${count} - 1")
    foreach(index RANGE 0 ${last_test})
      string(JSON name GET "${json}" tests ${index} name)
      if(name MATCHES "^cpu\\.vectors-full\\.")
        list(APPEND actual "${name}")
        if(name STREQUAL "cpu.vectors-full.fetch")
          set(fetch_index ${index})
        elseif(name STREQUAL "cpu.vectors-full.sample-match")
          set(sample_index ${index})
        endif()
        property_exists("${json}" ${index} DISABLED disabled)
        property_exists("${json}" ${index} SKIP_RETURN_CODE skip_code)
        if(disabled OR skip_code)
          set(${out_error} "full opcode/support test is disabled or skipped: ${name}" PARENT_SCOPE)
          return()
        endif()
        property_contains("${json}" ${index} LABELS "vectors-full" labelled)
        if(NOT labelled)
          set(${out_error} "full test lacks vectors-full label: ${name}" PARENT_SCOPE)
          return()
        endif()
        if(name MATCHES "^cpu\\.vectors-full\\.[0-9a-f][0-9a-f]$")
          property_contains("${json}" ${index} FIXTURES_REQUIRED "vectors_full" fixture)
          if(NOT fixture)
            set(${out_error} "full opcode lacks vectors_full fixture: ${name}" PARENT_SCOPE)
            return()
          endif()
        endif()
      endif()
    endforeach()
  endif()
  expected_names("cpu.vectors-full." expected_opcodes)
  set(expected ${expected_opcodes} cpu.vectors-full.fetch cpu.vectors-full.sample-match)
  list(SORT actual)
  list(SORT expected)
  if(NOT actual STREQUAL expected)
    set(missing ${expected})
    set(extra ${actual})
    foreach(name IN LISTS actual)
      list(REMOVE_ITEM missing "${name}")
    endforeach()
    foreach(name IN LISTS expected)
      list(REMOVE_ITEM extra "${name}")
    endforeach()
    set(${out_error} "vectors-full inventory mismatch; missing=${missing}; extra=${extra}" PARENT_SCOPE)
    return()
  endif()
  if(fetch_index LESS 0 OR sample_index LESS 0)
    set(${out_error} "vectors-full fetch and sample-match tests are required" PARENT_SCOPE)
    return()
  endif()
  property_contains("${json}" ${fetch_index} FIXTURES_SETUP "vectors_full" fetch_setup)
  if(NOT fetch_setup)
    set(${out_error} "full fetch lacks vectors_full fixture setup" PARENT_SCOPE)
    return()
  endif()
  property_contains("${json}" ${sample_index} FIXTURES_REQUIRED "vectors_full" sample_fixture)
  if(NOT sample_fixture)
    set(${out_error} "sample-match lacks vectors_full fixture requirement" PARENT_SCOPE)
    return()
  endif()
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(synthetic_full_inventory mutation out_json)
  set(tests "{\"name\":\"cpu.vectors-full.fetch\",\"properties\":[{\"name\":\"FIXTURES_SETUP\",\"value\":[\"vectors_full\"]},{\"name\":\"LABELS\",\"value\":[\"vectors-full\"]}]},{\"name\":\"cpu.vectors-full.sample-match\",\"properties\":[{\"name\":\"FIXTURES_REQUIRED\",\"value\":[\"vectors_full\"]},{\"name\":\"LABELS\",\"value\":[\"vectors-full\"]}]}")
  expected_names("cpu.vectors-full." opcodes)
  foreach(name IN LISTS opcodes)
    if(mutation STREQUAL missing AND name STREQUAL "cpu.vectors-full.00")
      continue()
    endif()
    if(mutation STREQUAL extra AND name STREQUAL "cpu.vectors-full.00")
      set(name cpu.vectors-full.100)
    endif()
    set(properties "{\"name\":\"FIXTURES_REQUIRED\",\"value\":[\"vectors_full\"]},{\"name\":\"LABELS\",\"value\":[\"vectors-full\"]}")
    if(mutation STREQUAL disabled AND name STREQUAL "cpu.vectors-full.01")
      string(APPEND properties ",{\"name\":\"DISABLED\",\"value\":true}")
    elseif(mutation STREQUAL skip AND name STREQUAL "cpu.vectors-full.01")
      string(APPEND properties ",{\"name\":\"SKIP_RETURN_CODE\",\"value\":77}")
    endif()
    string(APPEND tests ",{\"name\":\"${name}\",\"properties\":[${properties}]}")
  endforeach()
  set(${out_json} "{\"tests\":[${tests}]}" PARENT_SCOPE)
endfunction()

if(SELFTEST)
  foreach(mutation clean missing extra disabled skip)
    synthetic_full_inventory("${mutation}" inventory)
    check_full_inventory("${inventory}" error)
    if(mutation STREQUAL clean)
      if(error)
        message(FATAL_ERROR "clean synthetic inventory failed: ${error}")
      endif()
    elseif(NOT error)
      message(FATAL_ERROR "registration self-test did not detect ${mutation}")
    endif()
  endforeach()
  message(STATUS "vector registration policy self-test passed")
elseif(FULL_ONLY)
  if(DEFINED INVENTORY_FILE)
    if(NOT EXISTS "${INVENTORY_FILE}")
      message(FATAL_ERROR "cannot read saved CTest inventory: ${INVENTORY_FILE} is missing")
    endif()
    file(READ "${INVENTORY_FILE}" inventory)
  else()
    load_inventory("${FULL_BUILD}" inventory error)
    if(error)
      message(FATAL_ERROR "${error}")
    endif()
  endif()
  check_full_inventory("${inventory}" error)
  if(error)
    message(FATAL_ERROR "vector registration policy: ${error}")
  endif()
elseif(DEFINED SOURCE_DIR AND DEFINED CI_BUILD AND DEFINED FULL_BUILD)
  # Configure only. D-19/D-22 put fetching behind the full-tier test fixture.
  execute_process(COMMAND "${CMAKE_COMMAND}" --preset vectors-full
    WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE configure_status
    OUTPUT_VARIABLE configure_out ERROR_VARIABLE configure_err)
  if(NOT configure_status EQUAL 0)
    message(FATAL_ERROR "vectors-full configure failed (${configure_status}): ${configure_err}")
  endif()
  load_inventory("${CI_BUILD}" ci_inventory error)
  if(error)
    message(FATAL_ERROR "${error}")
  endif()
  check_ci_inventory("${ci_inventory}" error)
  if(error)
    message(FATAL_ERROR "vector registration policy: ${error}")
  endif()
  load_inventory("${FULL_BUILD}" full_inventory error)
  if(error)
    message(FATAL_ERROR "${error}")
  endif()
  check_full_inventory("${full_inventory}" error)
  if(error)
    message(FATAL_ERROR "vector registration policy: ${error}")
  endif()
  message(STATUS "vector registration policy passed")
else()
  message(FATAL_ERROR "SOURCE_DIR, CI_BUILD and FULL_BUILD are required")
endif()
