cmake_minimum_required(VERSION 3.25)

# Phase 8 baseline: this SHA-256 follows the mapper-0 API, nesturbator_reset, the save API
# and behaviour revision 5 (the PPU fetch pipeline). It is a temporary guard,
# not a permanent repository freeze.
set(PHASE8_DECLARATIONS_SHA256 "7ec4ca9a124042f9a64d090c4362af019c2b9773cb2aaf901683c0daade2d7f0")

function(normalize_api source out_hash)
  string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" text "${source}")
  string(REGEX REPLACE "//[^\n\r]*" "" text "${text}")
  string(REGEX REPLACE "#[ \t]*define[ \t]+NESTURBATOR_VERSION_(MAJOR|MINOR|PATCH)[^\n\r]*" "" text "${text}")
  string(REGEX REPLACE "[ \t\r\n]+" "" text "${text}")
  string(SHA256 digest "${text}")
  set(${out_hash} "${digest}" PARENT_SCOPE)
endfunction()

function(check_api source out_error)
  normalize_api("${source}" actual)
  if(NOT actual STREQUAL PHASE8_DECLARATIONS_SHA256)
    set(${out_error} "public declaration stream changed (expected ${PHASE8_DECLARATIONS_SHA256}, found ${actual})" PARENT_SCOPE)
  else()
    set(${out_error} "" PARENT_SCOPE)
  endif()
endfunction()

if(SELFTEST)
  if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SELFTEST requires SOURCE_DIR")
  endif()
  file(READ "${SOURCE_DIR}/include/nesturbator.h" header)
  check_api("${header}" error)
  if(error)
    message(FATAL_ERROR "clean header rejected: ${error}")
  endif()
  check_api("${header}\nvoid nesturbator_phase3_mutation(void);\n" error)
  if(NOT error)
    message(FATAL_ERROR "self-test did not detect an added public declaration")
  endif()
  message(STATUS "vector API policy mutation self-test passed")
elseif(DEFINED SOURCE_DIR)
  file(READ "${SOURCE_DIR}/include/nesturbator.h" header)
  check_api("${header}" error)
  if(error)
    message(FATAL_ERROR "vector API policy: ${error}")
  endif()
  message(STATUS "vector API policy passed")
else()
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
