cmake_minimum_required(VERSION 3.25)

# Phase 2 API freeze: this SHA-256 is the normalized declaration stream from
# the Phase 1 header. Phase 3 must replace or retire it when the public API
# changes; this is not a permanent repository-wide freeze.
set(PHASE1_DECLARATIONS_SHA256 "c0430712dcc8f498be9595cfd06de7b0355410eeb780d985c49ff01cee7c9899")

function(normalize_api source out_hash)
  string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" text "${source}")
  string(REGEX REPLACE "//[^\n\r]*" "" text "${text}")
  string(REGEX REPLACE "#[ \t]*define[ \t]+NESTURBATOR_VERSION_(MAJOR|MINOR|PATCH)[^\n\r]*" "" text "${text}")
  string(REGEX REPLACE "[ \t\r\n]+" "" text "${text}")
  string(SHA256 digest "${text}")
  set(${out_hash} "${digest}" PARENT_SCOPE)
endfunction()

function(check_api source out_error)
  normalize_api("${source}" actual)
  if(NOT actual STREQUAL PHASE1_DECLARATIONS_SHA256)
    set(${out_error} "public declaration stream changed (expected ${PHASE1_DECLARATIONS_SHA256}, found ${actual})" PARENT_SCOPE)
  else()
    set(${out_error} "" PARENT_SCOPE)
  endif()
endfunction()

if(SELFTEST)
  if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SELFTEST requires SOURCE_DIR")
  endif()
  file(READ "${SOURCE_DIR}/include/nesturbator.h" header)
  check_api("${header}" error)
  if(error)
    message(FATAL_ERROR "clean header rejected: ${error}")
  endif()
  check_api("${header}\nvoid nesturbator_phase3_mutation(void);\n" error)
  if(NOT error)
    message(FATAL_ERROR "self-test did not detect an added public declaration")
  endif()
  message(STATUS "vector API policy mutation self-test passed")
elseif(DEFINED SOURCE_DIR)
  file(READ "${SOURCE_DIR}/include/nesturbator.h" header)
  check_api("${header}" error)
  if(error)
    message(FATAL_ERROR "vector API policy: ${error}")
  endif()
  message(STATUS "vector API policy passed")
else()
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
