/* Declarations shared by the core's source files. Not installed.
   The core holds no mutable static or global variable: all state is here. */
#ifndef NESTURBATOR_INTERNAL_H
#define NESTURBATOR_INTERNAL_H

#include "nesturbator.h"

/* Time unit: one tick is half a master-clock period; NTSC has 24 ticks per
   CPU cycle and 8 per PPU dot (ARCHITECTURE section 2). An average NTSC frame
   is 89341 and a half dots, 714732 ticks, which is exactly the reported frame rate
   39375000/655171 (01-RESEARCH Open Question 1). */
#define NESTURBATOR_TICKS_PER_FRAME 714732u

/* Audio: 352 samples at 48000 Hz per 13125 CPU cycles, that is per 315000
   ticks (D-09, 01-RESEARCH Pattern 2). */
#define NESTURBATOR_AUDIO_SAMPLES_PER_PERIOD 352u
#define NESTURBATOR_AUDIO_TICKS_PER_PERIOD 315000u

/* Video output size in pixels. */
#define NESTURBATOR_WIDTH 256u
#define NESTURBATOR_HEIGHT 240u

/* Size of each boundary struct as first released. These equal this build's
   sizeof today; they stay fixed when fields are appended later. */
#define NESTURBATOR_VERSION_SIZE_V1 ((uint32_t)sizeof(nesturbator_version))
#define NESTURBATOR_CONFIG_SIZE_V1 ((uint32_t)sizeof(nesturbator_config))
#define NESTURBATOR_INFO_SIZE_V1 ((uint32_t)sizeof(nesturbator_info))
#define NESTURBATOR_FRAME_SIZE_V1 ((uint32_t)sizeof(nesturbator_frame))

struct nesturbator {
    nesturbator_allocator allocator; /* copy of the config's, defaults filled in */
    uint64_t frame_number;           /* frames run since create */
    uint64_t ticks;                  /* ticks run since create */
    uint32_t audio_rem;              /* sample fraction carried over, in units
                                        of 1/315000 sample per tick */
};

/* Validates an input struct's size tag before any other field is read.
   's' points at the struct; 'first' is its first released size; 'ours' is
   sizeof in this build. Returns NESTURBATOR_OK or
   NESTURBATOR_ERR_STRUCT_SIZE. */
nesturbator_status nesturbator__check_size_in(const void *s, uint32_t first, uint32_t ours);

/* The no-cartridge test card: native pixel at column x, row y (D-01, D-02). */
uint16_t nesturbator__test_pixel(uint32_t x, uint32_t y);

/* Native pixel to XRGB8888 0x00RRGGBB, generated by tools/palgen from NTSC
   signal facts (D-12, D-13). */
extern const uint32_t nesturbator__palette_ntsc[512];

#endif /* NESTURBATOR_INTERNAL_H */
